require('./bootstrap');
require('slick-carousel')
require('./header');
require('./message');
require('./feedback');
require('./login');
require('./register');
require('./filter');
require('./review')
require('./profile')
